#include <ctr11/ctr_console.h>
#include <ctr11/ctr_screen.h>
#include <ctr11/ctr_freetype.h>
#include <ctr11/ctr_pxi.h>

#include <stdint.h>

#define PDN_GPU_CNT (*(volatile uint32_t*)0x10141200)
#define LCD_REG(offset) (*((volatile uint32_t*)(0x10202000 + (offset))))
#define LCD_TOP_CONF_REG(offset) (*((volatile uint32_t*)(0x10202200 + (offset))))
#define LCD_BOT_CONF_REG(offset) (*((volatile uint32_t*)(0x10202A00 + (offset))))

#define LCD_TOP_CONF_BRIGHTNESS LCD_TOP_CONF_REG(0x40)
#define LCD_BOT_CONF_BRIGHTNESS LCD_BOT_CONF_REG(0x40)

#define PDC0_FRAMEBUFFER_SETUP_REG(offset) (*((volatile uint32_t*)(0x10400400 + (offset))))
#define PDC1_FRAMEBUFFER_SETUP_REG(offset) (*((volatile uint32_t*)(0x10400500 + (offset))))

#define PDC0_FRAMEBUFFER_SETUP_DIMS PDC0_FRAMEBUFFER_SETUP_REG(0x5C)
#define PDC0_FRAMEBUFFER_SETUP_FBA_ADDR_1 PDC0_FRAMEBUFFER_SETUP_REG(0x68)
#define PDC0_FRAMEBUFFER_SETUP_FBA_ADDR_2 PDC0_FRAMEBUFFER_SETUP_REG(0x6C)
#define PDC0_FRAMEBUFFER_SETUP_FB_FORMAT PDC0_FRAMEBUFFER_SETUP_REG(0x70)
#define PDC0_FRAMEBUFFER_SETUP_FB_SELECT PDC0_FRAMEBUFFER_SETUP_REG(0x78)
#define PDC0_FRAMEBUFFER_SETUP_DISCO PDC0_FRAMEBUFFER_SETUP_REG(0x84)
#define PDC0_FRAMEBUFFER_SETUP_FB_STRIDE PDC0_FRAMEBUFFER_SETUP_REG(0x90)
#define PDC0_FRAMEBUFFER_SETUP_FBB_ADDR_1 PDC0_FRAMEBUFFER_SETUP_REG(0x94)
#define PDC0_FRAMEBUFFER_SETUP_FBB_ADDR_2 PDC0_FRAMEBUFFER_SETUP_REG(0x98)

#define PDC1_FRAMEBUFFER_SETUP_DIMS PDC1_FRAMEBUFFER_SETUP_REG(0x5C)
#define PDC1_FRAMEBUFFER_SETUP_FBA_ADDR_1 PDC1_FRAMEBUFFER_SETUP_REG(0x68)
#define PDC1_FRAMEBUFFER_SETUP_FBA_ADDR_2 PDC1_FRAMEBUFFER_SETUP_REG(0x6C)
#define PDC1_FRAMEBUFFER_SETUP_FB_FORMAT PDC1_FRAMEBUFFER_SETUP_REG(0x70)
#define PDC1_FRAMEBUFFER_SETUP_FB_SELECT PDC1_FRAMEBUFFER_SETUP_REG(0x78)
#define PDC1_FRAMEBUFFER_SETUP_DISCO PDC1_FRAMEBUFFER_SETUP_REG(0x84)
#define PDC1_FRAMEBUFFER_SETUP_FB_STRIDE PDC1_FRAMEBUFFER_SETUP_REG(0x90)
#define PDC1_FRAMEBUFFER_SETUP_FBB_ADDR_1 PDC1_FRAMEBUFFER_SETUP_REG(0x94)
#define PDC1_FRAMEBUFFER_SETUP_FBB_ADDR_2 PDC1_FRAMEBUFFER_SETUP_REG(0x98)

void __attribute__((weak)) ctr_libctr11_init(void);

void __attribute__((weak)) ctr_libctr11_init(void)
{
	// FIXME we should do GPU/LCD/display init properly here
	ctr_pxi_initialize();
	ctr_screen_initialize(&ctr_screen_top, (uint8_t*)PDC0_FRAMEBUFFER_SETUP_FBA_ADDR_1, 400, 240, CTR_GFX_PIXEL_RGB8);
	ctr_screen_initialize(&ctr_screen_bottom, (uint8_t*)PDC1_FRAMEBUFFER_SETUP_FBA_ADDR_1, 320, 240, CTR_GFX_PIXEL_RGB8);
	ctr_console_initialize(&ctr_screen_top);

	ctr_freetype_initialize();
	ctr_pxi_push((unsigned int)PDC0_FRAMEBUFFER_SETUP_FBA_ADDR_1);
	ctr_pxi_push((unsigned int)PDC1_FRAMEBUFFER_SETUP_FBA_ADDR_1);
}

